---
abstract: 'Interface to the Singapore Metro Map.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  Test::Map::Tube: 0.35
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Map-Tube-Singapore
no_index:
  directory:
    - examples
    - inc
    - share
    - t
    - xt
requires:
  File::Share: 0
  Map::Tube: '3.62'
  Moo: 0
  namespace::clean: 0
  perl: 5.6.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Map-Tube-Singapore
  homepage: https://github.com/michal-josef-spacek/Map-Tube-Singapore
  license: http://opensource.org/licenses/artistic-license-2.0.php
  repository: git://github.com/michal-josef-spacek/Map-Tube-Singapore
version: '0.06'
